### testando raiz do programa
GET http://localhost:5205


### Criação de um novo funcionário
POST http://localhost:5205/api/funcionarios/cadastrar
Content-Type: application/json

{
    "nome": "Joao",
    "cpf" : "12345678912"
}

### Obtenção de todos os funcionários
GET http://localhost:5205/api/funcionarios/listar

# FOLHA ############################################

### Criação de uma nova folha
POST http://localhost:5205/api/folhas/cadastrar
Content-Type: application/json

{
    "valor": 50,
    "quantidade" : 1000,
    "mes" : 10,
    "ano" : 2023,
    "funcionarioId" : 1
}

### Obtenção de todas as folhas
GET http://localhost:5205/api/folhas/listar

### Obtenção de uma folha
GET http://localhost:5205/api/folhas/buscar/12345678912/10/2023